name: Deploy Next.js to NAS using Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and Push Docker image
      run: |
        docker build -t dudnjsckrgo/virtual-idol-frontend:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push dudnjsckrgo/virtual-idol-frontend:latest

    - name: Deploy to NAS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.NAS_HOST }}
        username: ${{ secrets.NAS_USER }}
        key: ${{ secrets.NAS_KEY }}
        port: ${{ secrets.NAS_PORT }}
        script: |
          export PATH=/usr/local/bin:$PATH
          cd /var/services/homes/dudnjsckrgo/docker/virtual-front
          docker-compose pull
          docker-compose down
          docker-compose up -d
